# build environment
FROM node:19.8.1-alpine as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./

RUN npm install --package-lock-only && npm prune && npm ci
RUN npm install react-scripts@5.0.1 -g --silent

COPY . ./

RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]